apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-8q1h
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-8q1h
    app.kubernetes.io/part-of: my-app-1
  name: devfile-sample-code-with-quarkus-8q1h
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus-8q1h
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus-8q1h
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/abhindas-tenant/my-app-1/devfile-sample-code-with-quarkus-8q1h@sha256:4bf41fa715f38d0c0bb91be36cac4158a401a5fc35f58d1f733e7da6b9a8a068
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
