apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-e6oo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-e6oo
    app.kubernetes.io/part-of: my-app-1
  name: devfile-sample-e6oo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-e6oo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-e6oo
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/abhindas-tenant/my-app-1/devfile-sample-e6oo@sha256:497e3c3a903297ea7a10cc44396a0ec39f880a353efc6f737942f1ec5c7b121e
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
